services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/var/lib/mariadb'

volumes:
  mariadb_data: